language: python
python:
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - pip install --upgrade pip pytest coverage coveralls
  - pip install .
script: coverage run --source=pipes -m py.test -l -v pipes/
after_success: coveralls