language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install --upgrade pip pytest coverage coveralls
  - pip install .
script: coverage run --source=aiopipes -m py.test -l -v test/
after_success: coveralls